import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_ASSETS = path.join(__dirname, '../src/assets');
const PUBLIC_ASSETS = path.join(__dirname, '../public/assets');
const SRC_COUPLE = path.join(SRC_ASSETS, 'couple_photo');
const PUBLIC_COUPLE = path.join(PUBLIC_ASSETS, 'couple_photo');

async function copyRecursive(src, dest, skipDir = null) {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    if (skipDir && entry.name === skipDir) continue;
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      await copyRecursive(srcPath, destPath);
    } else {
      await fs.copyFile(srcPath, destPath);
    }
  }
}

async function main() {
  try {
    // 1. Copy all assets EXCEPT couple_photo (we'll handle it below)
    await copyRecursive(SRC_ASSETS, PUBLIC_ASSETS, 'couple_photo');

    // 2. Read config to get couplePhotos order and copy with URL-safe names
    const configPath = path.join(__dirname, '../config.json');
    let couplePhotoUrls = [];
    try {
      const configRaw = await fs.readFile(configPath, 'utf-8');
      const config = JSON.parse(configRaw);
      const photos = config.couplePhotos;
      if (Array.isArray(photos) && photos.length > 0) {
        await fs.mkdir(PUBLIC_COUPLE, { recursive: true });
        for (let i = 0; i < photos.length; i++) {
          const item = photos[i];
          const imagePath = item?.image;
          if (!imagePath || typeof imagePath !== 'string') continue;
          const filename = imagePath.split('/').pop();
          if (!filename) continue;
          const ext = path.extname(filename) || '.jpg';
          const srcFile = path.join(SRC_COUPLE, filename);
          const safeName = `couple_photo_${i + 1}${ext}`;
          const destFilePublic = path.join(PUBLIC_COUPLE, safeName);
          const destFileSrc = path.join(SRC_COUPLE, safeName);
          try {
            await fs.copyFile(srcFile, destFilePublic);
            await fs.copyFile(srcFile, destFileSrc);
            couplePhotoUrls.push(`/assets/couple_photo/${safeName}`);
          } catch (e) {
            console.warn(`⚠ Could not copy couple photo: ${filename} - ${e.message}`);
          }
        }
      }
    } catch (e) {
      console.warn('⚠ Could not read config.json for couple photos:', e.message);
    }

    // 3. Write generated URLs so the app can use them (no spaces in filenames)
    const generatedPath = path.join(__dirname, '../src/couple-photo-urls.generated.js');
    const content = `// Auto-generated by scripts/copy-assets.js - do not edit
export const couplePhotoUrls = ${JSON.stringify(couplePhotoUrls, null, 2)};
`;
    await fs.writeFile(generatedPath, content, 'utf-8');

    console.log('✅ Copied src/assets to public/assets');
    if (couplePhotoUrls.length) {
      console.log(`✅ Couple photos: ${couplePhotoUrls.length} copied with URL-safe names`);
    }
  } catch (err) {
    console.error('❌ copy-assets failed:', err.message);
    process.exit(1);
  }
}

main();
